baseURL: "/"
title: TEXP Wiki
paginate: 5
theme: PaperMod
canonifyURLs: false
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
languageCode: "en-US"
footnoteReturnLinkContents: '↩'
paginate: 7
rssLimit: 10
publishDir: 'paper'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: TEXP Wiki
    titleSeparator: "-"
    titleAddition: "Crushing it on Documentation!"
    description: "A documentation powerhouse & reliable resource enabling YOU to be a total expert in our TE platform! 🤓"
    keywords: [Blog, Portfolio, PaperMod, Total Expert, Wiki, Knowledge Base]
    author: BatmanWGD
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2021"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    disableAliases: true
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: true
    hideSummary: false
    showtoc: false
    tocopen: false
    ## Open Graph + Twitter Cards
    images: ["doks.png"]
    twitterSite: "batmanwgd"
    twitterCreator: "batmanwgd"
    facebookAuthor: "batmanwgd"
    facebookPublisher: "batmanwgd"
    ogLocale: "en_US"
    ## JSON-LD
    schemaType: "Organization"
    schemaLogo: "logo-doks.png"
    schemaTwitter: "https://twitter.com/batmanwgd"
    schemaLinkedIn: "https://www.linkedin.com/in/stddef/"
    schemaGitHub: "https://github.com/batmanwgd"
    schemaSection: "blog"
    ## Sitelinks Search Box
    siteLinksSearchBox: false
    ## Chrome Browser
    themeColor: "#fff"
    # Footer
    love: "Made with  💖 by <a href=\"https://github.com/batmanwgd/\">@batmanwgd</a>"
    footer: "Powered by <a href=\"https://pages.github.com/\">GitHub</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"


    assets:
        # disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        feather: "<link / abs url>"
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: TEXP Wiki
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to TEXP

    socialIcons:
        - name: twitter
          url: "https://twitter.com/"
        - name: stackoverflow
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: dictionary
          name: dictionary
          url: /dictionary/
          weight: 30
        - identifier: Concepta
          name: concepta.netlify.app
          url: https://concepta.netlify.app
          weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        anchorLineNos: true
        hl_Lines: ""
        lineNoStart: 1
        noClasses: false
        codeFences: false
        guessSyntax: true
        lineNos: true
        style: monokai
        tabWidth: 4

build:
  writeStats: true

